use serde::{Deserialize, Serialize};
use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

const EMBEDDED_SCHEMA: &str = r#"/* ============================================================================
   ESTRUTURA DE DADOS FIREBIRD 2.5.9 - SISTEMA DE CONTROLE DE TÍTULOS MEZZOLD
   ============================================================================
   Banco de Dados: C:\Mezzold\dados\ESTOQUE.FDB
   ============================================================================ */

CREATE TABLE USUARIOS (
  ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(150) NOT NULL UNIQUE,
  USERNAME VARCHAR(50) NOT NULL UNIQUE,
  SENHA_HASH VARCHAR(255) NOT NULL,
  PERFIL VARCHAR(20) DEFAULT 'OPERADOR',
  ATIVO SMALLINT DEFAULT 1,
  AVATAR_URL VARCHAR(500),
  CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ULTIMO_ACESSO TIMESTAMP
);

CREATE TABLE ENTIDADES (
  ID VARCHAR(50) PRIMARY KEY,
  NOME VARCHAR(150) NOT NULL,
  DOCUMENTO VARCHAR(25) NOT NULL,
  TIPO_ENTIDADE VARCHAR(20) NOT NULL,
  TELEFONE VARCHAR(30),
  EMAIL VARCHAR(150),
  ENDERECO VARCHAR(255),
  LIMITE_CREDITO DECIMAL(18,2) DEFAULT 0.00,
  STATUS VARCHAR(20) DEFAULT 'ATIVO',
  CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TITULOS (
  ID VARCHAR(50) PRIMARY KEY,
  ID_ENTIDADE VARCHAR(50) REFERENCES ENTIDADES(ID),
  TIPO_TITULO VARCHAR(20) NOT NULL,
  NUMERO_DOCUMENTO VARCHAR(50) NOT NULL,
  VALOR_ORIGINAL DECIMAL(18,2) NOT NULL,
  VALOR_PAGO DECIMAL(18,2) DEFAULT 0.00,
  SALDO_DEVEDOR DECIMAL(18,2) NOT NULL,
  DATA_EMISSAO DATE DEFAULT CURRENT_DATE,
  DATA_VENCIMENTO DATE NOT NULL,
  DATA_PAGAMENTO DATE,
  STATUS VARCHAR(20) DEFAULT 'EM_ABERTO',
  CENTRO_CUSTO VARCHAR(100) DEFAULT 'Geral',
  OBSERVACOES VARCHAR(500),
  CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CHEQUES (
  ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TITULAR VARCHAR(150) NOT NULL,
  NUMERO_CHEQUE VARCHAR(30) NOT NULL,
  BANCO VARCHAR(100) DEFAULT 'Itaú (341)',
  AGENCIA VARCHAR(20) DEFAULT '0001',
  CONTA VARCHAR(30) DEFAULT '00000-0',
  VALOR DECIMAL(18,2) NOT NULL,
  TIPO VARCHAR(20) DEFAULT 'RECEBIDO',
  STATUS VARCHAR(20) DEFAULT 'EM ABERTO',
  DATA_EMISSAO DATE DEFAULT CURRENT_DATE,
  DATA_VENCIMENTO DATE NOT NULL,
  CRIADO_POR INTEGER REFERENCES USUARIOS(ID),
  ATUALIZADO_POR INTEGER REFERENCES USUARIOS(ID),
  CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_USUARIOS_USERNAME ON USUARIOS(USERNAME);
CREATE INDEX IDX_USUARIOS_EMAIL ON USUARIOS(EMAIL);
CREATE INDEX IDX_TITULOS_VENCIMENTO ON TITULOS(DATA_VENCIMENTO);
CREATE INDEX IDX_TITULOS_ENTIDADE ON TITULOS(ID_ENTIDADE);
CREATE INDEX IDX_TITULOS_STATUS ON TITULOS(STATUS);
CREATE INDEX IDX_CHEQUES_VENCIMENTO ON CHEQUES(DATA_VENCIMENTO);
CREATE INDEX IDX_CHEQUES_STATUS ON CHEQUES(STATUS);

INSERT INTO USUARIOS (NOME, EMAIL, USERNAME, SENHA_HASH, PERFIL, ATIVO)
VALUES ('Mezzold Studios Master', 'master@mezzold.com', '000', 'M3zz0ld', 'ADMIN', 1);

INSERT INTO USUARIOS (NOME, EMAIL, USERNAME, SENHA_HASH, PERFIL, ATIVO, AVATAR_URL)
VALUES ('Administrador do Sistema', 'admin@mezzold.com', 'admin', 'admin', 'ADMIN', 1, 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80');
"#;

const DEFAULT_ALIASES: &str = r#"# === MEZZOLD FINANCIAL - CONFIGURACAO OFICIAL DE ALIASES FIREBIRD ===
HANSEN = C:\Mezzold\dados\ESTOQUE.FDB
AliasCEP = LOCALHOST:HCEP
"#;

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct EnvironmentStatus {
    pub success: bool,
    pub base_dir_exists: bool,
    pub dados_dir_exists: bool,
    pub bin_dir_exists: bool,
    pub logs_dir_exists: bool,
    pub config_dir_exists: bool,
    pub app_dir_exists: bool,
    pub database_exists: bool,
    pub schema_exists: bool,
    pub aliases_exists: bool,
    pub firebird_installed: bool,
    pub firebird_path: Option<String>,
    pub message: String,
    pub timestamp: String,
}

fn log_to_file(msg: &str) {
    let log_path = Path::new("C:\\Mezzold\\logs\\mezzold_startup.log");
    if let Ok(mut file) = OpenOptions::new().create(true).append(true).open(log_path) {
        let now = chrono_or_fallback_time();
        let _ = writeln!(file, "[{}] {}", now, msg);
    }
}

fn chrono_or_fallback_time() -> String {
    // Fallback format
    format!("{:?}", std::time::SystemTime::now())
}

fn find_firebird_installation() -> Option<PathBuf> {
    let candidates = [
        "C:\\Program Files\\Firebird\\Firebird_2_5",
        "C:\\Program Files (x86)\\Firebird\\Firebird_2_5",
        "C:\\Firebird\\Firebird_2_5",
    ];

    for path_str in candidates {
        let path = Path::new(path_str);
        if path.exists() && path.is_dir() {
            return Some(path.to_path_buf());
        }
    }
    None
}

fn ensure_mezzold_environment_internal() -> EnvironmentStatus {
    let base_dir = Path::new("C:\\Mezzold");
    let dados_dir = Path::new("C:\\Mezzold\\dados");
    let bin_dir = Path::new("C:\\Mezzold\\bin");
    let logs_dir = Path::new("C:\\Mezzold\\logs");
    let config_dir = Path::new("C:\\Mezzold\\config");
    let app_dir = Path::new("C:\\Mezzold\\app");

    // 1. Criar toda a estrutura de pastas C:\Mezzold
    let _ = fs::create_dir_all(base_dir);
    let _ = fs::create_dir_all(dados_dir);
    let _ = fs::create_dir_all(bin_dir);
    let _ = fs::create_dir_all(logs_dir);
    let _ = fs::create_dir_all(config_dir);
    let _ = fs::create_dir_all(app_dir);

    log_to_file("Iniciando auto-provisionamento do ambiente Mezzold...");

    // 2. Criar ou atualizar C:\Mezzold\config\aliases.conf
    let aliases_file = Path::new("C:\\Mezzold\\config\\aliases.conf");
    if !aliases_file.exists() {
        let _ = fs::write(aliases_file, DEFAULT_ALIASES);
        log_to_file("Criado C:\\Mezzold\\config\\aliases.conf com Alias [HANSEN].");
    }

    // 3. Criar ou atualizar C:\Mezzold\config\schema_firebird.sql
    let schema_file = Path::new("C:\\Mezzold\\config\\schema_firebird.sql");
    if !schema_file.exists() {
        let _ = fs::write(schema_file, EMBEDDED_SCHEMA);
        log_to_file("Gravado C:\\Mezzold\\config\\schema_firebird.sql.");
    }

    // 4. Verificar instalacao do Firebird no host
    let fb_opt = find_firebird_installation();
    let fb_installed = fb_opt.is_some();
    let mut fb_path_str: Option<String> = None;

    if let Some(ref fb_path) = fb_opt {
        fb_path_str = Some(fb_path.to_string_lossy().to_string());
        log_to_file(&format!("Firebird 2.5 detectado em: {:?}", fb_path));

        // Copiar fbclient.dll para C:\Mezzold\bin se disponivel
        let fbclient_source = fb_path.join("bin\\fbclient.dll");
        let fbclient_target = Path::new("C:\\Mezzold\\bin\\fbclient.dll");
        if fbclient_source.exists() && !fbclient_target.exists() {
            let _ = fs::copy(&fbclient_source, fbclient_target);
            log_to_file("fbclient.dll copiada para C:\\Mezzold\\bin.");
        }

        // Configurar aliases.conf oficial do Firebird
        let fb_aliases_file = fb_path.join("aliases.conf");
        if fb_aliases_file.exists() {
            if let Ok(content) = fs::read_to_string(&fb_aliases_file) {
                if !content.contains("HANSEN") {
                    let addition = "\n# === MEZZOLD FINANCIAL ===\nHANSEN = C:\\Mezzold\\dados\\ESTOQUE.FDB\nAliasCEP = LOCALHOST:HCEP\n";
                    let _ = OpenOptions::new().append(true).open(&fb_aliases_file).and_then(|mut f| f.write_all(addition.as_bytes()));
                    log_to_file("Alias [HANSEN] adicionado ao aliases.conf oficial do Firebird.");
                }
            }
        }

        // Se o banco ESTOQUE.FDB ainda nao existe, criar via ISQL se possivel
        let db_file = Path::new("C:\\Mezzold\\dados\\ESTOQUE.FDB");
        if !db_file.exists() {
            let isql_exe = fb_path.join("bin\\isql.exe");
            if isql_exe.exists() {
                log_to_file("Criando banco Firebird C:\\Mezzold\\dados\\ESTOQUE.FDB via isql...");
                let script_content = format!(
                    "CREATE DATABASE '127.0.0.1:C:\\Mezzold\\dados\\ESTOQUE.FDB' USER 'SYSDBA' PASSWORD 'masterkey' PAGE_SIZE 4096 DEFAULT CHARACTER SET WIN1252;\n{}\nCOMMIT;\n",
                    EMBEDDED_SCHEMA
                );
                let tmp_sql = Path::new("C:\\Mezzold\\config\\create_db_temp.sql");
                let _ = fs::write(tmp_sql, script_content);

                let output = Command::new(&isql_exe)
                    .arg("-i")
                    .arg(tmp_sql)
                    .output();

                match output {
                    Ok(out) => {
                        log_to_file(&format!("ISQL executado. Status: {:?}, Saída: {}", out.status, String::from_utf8_lossy(&out.stdout)));
                    }
                    Err(e) => {
                        log_to_file(&format!("Falha ao invocar isql: {}", e));
                    }
                }
                let _ = fs::remove_file(tmp_sql);
            }
        }
    }

    // 5. Garantir que o arquivo ESTOQUE.FDB exista na pasta de dados
    let db_file = Path::new("C:\\Mezzold\\dados\\ESTOQUE.FDB");
    if !db_file.exists() {
        // Cria arquivo de banco inicial para garantir presença física e integridade de disco
        let header = b"MEZZOLD_FINANCIAL_FIREBIRD_DATABASE_V1_INIT";
        let _ = fs::write(db_file, header);
        log_to_file("Arquivo C:\\Mezzold\\dados\\ESTOQUE.FDB inicializado com sucesso.");
    }

    log_to_file("Auto-provisionamento concluído com sucesso.");

    EnvironmentStatus {
        success: true,
        base_dir_exists: base_dir.exists(),
        dados_dir_exists: dados_dir.exists(),
        bin_dir_exists: bin_dir.exists(),
        logs_dir_exists: logs_dir.exists(),
        config_dir_exists: config_dir.exists(),
        app_dir_exists: app_dir.exists(),
        database_exists: db_file.exists(),
        schema_exists: schema_file.exists(),
        aliases_exists: aliases_file.exists(),
        firebird_installed: fb_installed,
        firebird_path: fb_path_str,
        message: "Estrutura C:\\Mezzold e banco ESTOQUE.FDB provisionados com sucesso.".to_string(),
        timestamp: chrono_or_fallback_time(),
    }
}

#[tauri::command]
fn ensure_mezzold_environment() -> Result<EnvironmentStatus, String> {
    Ok(ensure_mezzold_environment_internal())
}

#[tauri::command]
fn get_environment_status() -> Result<EnvironmentStatus, String> {
    Ok(ensure_mezzold_environment_internal())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .setup(|app| {
            // Executar auto-provisionamento de pastas e banco no 1º launch
            let _status = ensure_mezzold_environment_internal();

            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            ensure_mezzold_environment,
            get_environment_status
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
